### ISSUE TITLE
Add an environment variable lookup YAML tag

### ISSUE THREAD

**Issue by hamidnazari** [Innablr/cloudformation-seed#25]
For example,

```
stacks:
  - name: in-cld-managed-zone
    template: centralservices/r53-zone.cf.yaml
    parameters:
      ManagedZoneDomainName: !EnvironmentVariable DOMAIN_NAME
```

where DOMAIN_NAME is an environment variable. In case it's not set, an empty string should be returned.
