### ISSUE TITLE
Configurable StackSet Operation Preferences

### ISSUE THREAD

**Issue by hamidnazari** [Innablr/cloudformation-seed#7]
Allow StackSet OperationPreferences to be configured in runbooks, for RegionOrder, FailureToleranceCount, FailureTolerancePercentage, MaxConcurrentCount, and MaxConcurrentPercentage.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html

**Comment by abukharov** [comment]
Already supported:

```
  - name: sharedservices-proxy-endpoints-set
    type: stackset
    template: sets/proxy-endpoints.cf.yaml
    operation_preferences:
      max_concurrent: 100%
      failure_tolerance: 100%
    parameters:
      SharedServicesAcceptEndpointRequestRoleArn: !StackOutput sharedservices-proxy-farm.AcceptEndpointSubscriptionRoleArn
```

**Comment by abukharov** [comment]
Already supported:

```
  - name: sharedservices-proxy-endpoints-set
    type: stackset
    template: sets/proxy-endpoints.cf.yaml
    operation_preferences:
      max_concurrent: 100%
      failure_tolerance: 100%
    parameters:
      SharedServicesAcceptEndpointRequestRoleArn: !StackOutput sharedservices-proxy-farm.AcceptEndpointSubscriptionRoleArn
```
