### ISSUE TITLE
Add support for substring variables within parameter values

### ISSUE THREAD

**Issue by jbarnes** [Innablr/cloudformation-seed#72]
Currently you can only allocate a singular variable to a parameter key.

This enhancement requests the ability to add/use variables as a substring value for a parameter. The main benefit of this is to allow for a singular set of parameter values that can be applicable to a wide range of stacks that carry some variance.

Example

```yaml
      CustomerName: *CUSTOMER
      Parameter1: /prefix/*CUSTOMER/test/suffix1
      Parameter2: /prefix/*CUSTOMER/test/suffix2
      Parameter3: /prefix/*CUSTOMER/test/suffix3
```

In the above example the CUSTOMER variable is added as a substring to the parameters thus providing the ability to have a singular definition of parameters for multiple customers where the variable caters to these requirements versus having to hardcode every single customer name and have multiple sets of parameters defined for each.
